In [2]:
%pylab inline

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [14]:
K=array([[1,2,3],[4,5,6]])
v=array([1,0,0])

In [16]:
dot(K,v)

array([1, 4])

In [11]:
def row_normalize(K):
    return (K.T/(sum(K,axis=1))).T

In [20]:
def col_normalize(K):
    return (K/(sum(K,axis=0)))

In [21]:
row_normalize(K)

array([[0.16666667, 0.33333333, 0.5       ],
       [0.26666667, 0.33333333, 0.4       ]])

In [22]:
col_normalize(K)

array([[0.2       , 0.28571429, 0.33333333],
       [0.8       , 0.71428571, 0.66666667]])